version: '3.8'

services:
  web:
    image: nginx:latest
    container_name: fruitfresh-webapp
    restart: always
    ports:
      - "${WEBSITE_PORT}:80" 
    environment:
      DATABASE_HOST: ${DATABASE_HOST}  
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${MYSQL_ECOMMERCE_DB}
      DATABASE_USER: ${MYSQL_ECOMMERCE_USER}
      DATABASE_PASSWORD: ${MYSQL_ECOMMERCE_PASSWORD}
      NEXTCLOUD_URL: ${NEXTCLOUD_URL} 
    volumes:
      - /srv/website/data:/usr/share/nginx/html  
    depends_on: